# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('departure_city', models.CharField(max_length=30)),
                ('arrival_city', models.CharField(max_length=30)),
                ('departure_time', models.TimeField(verbose_name='departure time')),
                ('arrival_time', models.TimeField(verbose_name='arrival time')),
                ('departure_date', models.DateField(verbose_name='departure date')),
                ('arrival_date', models.DateField(verbose_name='arrival date')),
            ],
        ),
    ]
