# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20170306_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='name of flight', max_length=100),
        ),
    ]
